name: horus_develop
channels:
  - conda-forge
  - nostrumbiodiscovery
  - defaults
dependencies:
  - pip=23.1.2
  - python=3.9.16
  - cython=0.29.34
  - pyinstaller==5.10.1
  - flask==2.3.2
  - pip:
      - pywebview==4.1
      - pyobjc==9.1.1; sys_platform == 'darwin'


