# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "Horus"
copyright = "2025, BSC | Barcelona Supercomputing Center"
author = "Barcelona Supercomputing Center"

# HorusAPI source path
import os
import sys

sys.path.insert(0, os.path.abspath("../../"))
sys.path.append(os.path.abspath("../../../"))
import HorusAPI

release = HorusAPI.__version__

# Remove "-release if present"
if release.endswith("-release"):
    release = release.replace("-release", "")

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.autosectionlabel",
    "nbsphinx",
    "sphinx_copybutton",
    "sphinx_design",
]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["custom.css"]
templates_path = ["_templates"]

# -- Options --


source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "setup.py", "HorusAPI/__init__.py"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"
# html_theme = "sphinx_book_theme"
# html_static_path = ["_static"]
html_logo = "_static/horus.png"
html_favicon = "_static/horus.png"
html_show_sourcelink = False
html_show_sphinx = False
html_theme_options = {"collapse_navigation": True}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {
    # TODO not ready yet
    "show_nav_level": 1,
    "logo": {
        "text": "Horus",
        "image_dark": "horus.png",
        "alt_text": "Horus logo",
    },
    "icon_links": [
        {
            "name": "Barcelona Supercomputing Centre website",
            "url": "https://www.bsc.es/",
            "icon": "fa fa-globe",
        },
        {
            "name": "Twitter",
            "url": "https://www.twitter.com/EAPM_BSC",
            "icon": "fa-brands fa-twitter",
        },
        {
            "name": "Linkedin",
            "url": "https://www.linkedin.com/company/barcelona-supercomputing-center/",
            "icon": "fa-brands fa-linkedin",
        },
    ],
    # "switcher": {
    #    "json_url": "https://mysite.org/en/latest/_static/switcher.json",
    # }
}

add_module_names = False
autoclass_content = "both"
