name: horus
channels:
  - conda-forge
  - nostrumbiodiscovery
dependencies:
  - pip=23.1.2
  - python=3.9.16
  - pyinstaller==5.10.1
  - flask==2.3.2
  - requests==2.29.0
  - pip:
      - pywebview==4.1
      - flask-cors==3.0.10
      - pyobjc==9.1.1; sys_platform == 'darwin'
      - pygobject; sys_platform == 'linux'
      - pycairo; sys_platform == 'linux'
      - flask-socketio
      - eventlet
      - gevent
      - Cython==3.0.0b3
      - paramiko
      - pytest
      - pytest-mock
