name: horus_develop
channels:
  - conda-forge
  - nostrumbiodiscovery
dependencies:
  - pip=23.1.2
  - python=3.9.16
  - paramiko
  - pyinstaller==5.10.1
  - flask==2.3.2
  - requests==2.29.0
  - rdkit
  - openmm
  - scipy
  - tk
  - pip:
      - pywebview==4.1
      - flask-cors==3.0.10
      - pyobjc==9.1.1; sys_platform == 'darwin'
      - pygobject==3.44.1; sys_platform == 'linux'
      - pytest
      - flask-socketio
      - eventlet
      - gevent
      - Cython==3.0.0b3

# Manual install due to Apple Silicon/ARM not available from repo
# python -m pip install peleffy
# python -m pip install nbdsuite<version>.tar.gz



