name: Test and build Horus

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - name: Cleaning up
        run: |
          singularity exec --bind .:/app docker://chdominguez/horus_rocky npm run clean-all 
          singularity exec --bind .:/app docker://chdominguez/horus_rocky conda env remove -n horus_test -y
      - name: Install requirements
        run: |
          singularity exec --bind .:/app docker://chdominguez/horus_rocky npm install --legacy-peer-deps
          singularity exec --bind .:/app docker://chdominguez/horus_rocky conda env create -f Devtools/Environment/conda_horus.yaml -n horus_test
      - name: Build GUI with Rocky 8 image
        run: singularity exec --bind .:/app docker://chdominguez/horus_rocky npm run buildparcel
      - name: Test Horus with Rocky 8 image
        run: |
          singularity exec --bind .:/app docker://chdominguez/horus_rocky sh Devtools/Singularity/test_horus.sh
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Gather CI environment
        run: |
          export GIT_TAG=$(git describe --tags --abbrev=0)
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
          echo "Latest tag: $GIT_TAG"
          export GIT_BRANCH=$CI_HEAD_REF
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo "Branch: $GIT_BRANCH"
          export GIT_COMMIT=$CI_SHA_SHORT
          echo "GIT_COMMIT=$GIT_COMMIT" >> $GITHUB_ENV
          echo "Commit: $GIT_COMMIT"
          # Set the version as tag-branch-commit from the env
          # If the branch == tag, then the version is just the tag
          # If the branch != tag, then the version is tag-branch-commit
          if [ "$GIT_TAG" == "$GIT_BRANCH" ]; then
            export VERSION=$GIT_TAG
          else
            export VERSION=$GIT_TAG-$GIT_BRANCH-$GIT_COMMIT
          fi
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "Built version: $VERSION"
      - name: Build Rocky 8
        run: singularity run --bind .:/app docker://chdominguez/horus_rocky
      - name: Upload Rocky 8 artifact
        uses: actions/upload-artifact@v4
        with:
          name: Horus-${{ env.version }}-Rocky8-QT
          path: dist/*Rocky.tar.gz
      - name: Build Ubuntu 22.04
        run: singularity run --bind .:/app docker://chdominguez/horus_ubuntu
      - name: Upload Ubuntu 22 artifact
        uses: actions/upload-artifact@v4
        with:
          name: Horus-${{ env.version }}-Ubuntu22-GTK
          path: dist/*Ubuntu22.tar.gz
      - name: Build Linux Universal
        run: singularity run --bind .:/app docker://chdominguez/horus_universal
      - name: Upload Linux Universal artifact
        uses: actions/upload-artifact@v4
        with:
          name: Horus-${{ env.version }}-Linux-Universal
          path: dist/*Universal.tar.gz
