name: Test and build Horus

on:
  pull_request:
    branches: [main]

jobs:
  build-ubuntu:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: |
          npm run requirements-action
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          python-version: 3.9.16
          add-pip-as-python-dependency: true
          auto-activate-base: false
          environment-file: Devtools/Environment/conda_horus.yaml
          activate-environment: horus
      - name: Build GUI
        run: npm run buildparcel
      - name: Test
        run: |
          npm run test
      - name: Build
        run: |
          npm run build
      - name: Package
        run: |
          npm run distribute
          cd dist/Packages
          export FILENAME=$(ls *.deb)
          echo "filename=$FILENAME" >> $GITHUB_ENV
          echo "Produced artifact: $FILENAME"
      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.filename }}
          path: dist/Packages/*.deb
          if-no-files-found: error

  build-macos:
    permissions:
      contents: write
      pull-requests: write
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: |
          npm run requirements-action
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          python-version: 3.9.16
          add-pip-as-python-dependency: true
          auto-activate-base: false
          environment-file: Devtools/Environment/conda_horus.yaml
          activate-environment: horus
      - name: Build GUI
        run: npm run buildparcel
      - name: Test
        run: |
          npm run test
      - name: Build
        run: |
          npm run build
      - name: Package
        run: |
          npm run distribute
          cd dist/Packages
          export FILENAME=$(ls *.dmg)
          echo "filename=$FILENAME" >> $GITHUB_ENV
          echo "Produced artifact: $FILENAME"
      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.filename }}
          path: dist/Packages/*.dmg
          if-no-files-found: error
