name: Deploy HorusAPI documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  build_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    name: Build docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for all branches and tags
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: Devtools/Environment/conda_horus.yaml
          environment-name: horus_env
      - name: Build docs
        run: |
          cd HorusAPI/docs && make html
      - name: Deploy documentation
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: HorusAPI/docs/build/html
          user_name: "Christian Domínguez"
          user_email: "christian.99dominguez@gmail.com"
